// <copyright file="SourceFileGenerator.cs" company="SeminarioIA">
// Copyright (c) SeminarioIA. All rights reserved.
// </copyright>

using SourceGenerator.Generator.Types;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Text;

namespace SourceGenerator.Generator
{
    /// <summary>
    /// Source file generator class.
    /// </summary>
    public class SourceFileGenerator : SourceSnippet
    {
        /// <summary>
        /// The number of spaces for each identation step.
        /// </summary>
        public const int IndexationSpaces = 4;

        /// <summary>
        /// Initializes a new instance of the <see cref="SourceFileGenerator"/> class.
        /// </summary>
        /// <param name="name">The name of the new class.</param>
        /// <param name="namespace">Class namespace.</param>
        public SourceFileGenerator(string name, string @namespace)
            : base(null, name)
        {
            Namespace = @namespace;
            References = new Collection<string>();
            Snippets = new Collection<SourceSnippet>();
        }

        /// <summary>
        /// Gets the class namespace name.
        /// </summary>
        public string Namespace { get; }

        /// <summary>
        /// Gets the list of references.
        /// </summary>
        public Collection<string> References { get; }

        /// <summary>
        /// Gets the list of source code snippets contained in this file.
        /// </summary>
        public Collection<SourceSnippet> Snippets { get; }

        /// <summary>
        /// Adds a new using reference to the source code.
        /// </summary>
        /// <param name="reference">The reference to add.</param>
        /// <returns>This <see cref="SourceFileGenerator"/>.</returns>
        public SourceFileGenerator AddReference(string reference)
        {
            References.Add(reference);
            return this;
        }

        /// <summary>
        /// Adds a new <see cref="ClassSource"/> to the source file.
        /// </summary>
        /// <param name="access">The <see cref="ClassAccess"/> attributes.</param>
        /// <param name="scope">The <see cref="ClassScope"/> attributes.</param>
        /// <param name="name">The <see cref="ClassSource"/> name.</param>
        /// <returns>The new added <see cref="ClassSource"/>.</returns>
        public ClassSource AddClass(ClassAccess access, ClassScope scope, string name)
        {
            var @class = new ClassSource(this, access, scope, name);
            Snippets.Add(@class);
            return @class;
        }

        /// <summary>
        /// Adds a new <see cref="StructSource"/> to the source file.
        /// </summary>
        /// <param name="access">The <see cref="StructAccess"/> attributes.</param>
        /// <param name="scope">The <see cref="StructScope"/> attributes.</param>
        /// <param name="name">The <see cref="StructSource"/> name.</param>
        /// <returns>The new added <see cref="StructSource"/>.</returns>
        public StructSource AddStruct(StructAccess access, StructScope scope, string name)
        {
            var @class = new StructSource(this, access, scope, name);
            Snippets.Add(@class);
            return @class;
        }

        /// <summary>
        /// Adds a new <see cref="EnumSource"/> to the source file.
        /// </summary>
        /// <param name="access">The <see cref="EnumAccess"/> attributes.</param>
        /// <param name="name">The <see cref="EnumSource"/> name.</param>
        /// <returns>The new added <see cref="EnumSource"/>.</returns>
        public EnumSource AddEnum(EnumAccess access, string name)
        {
            var @enum = new EnumSource(this, access, name);
            Snippets.Add(@enum);
            return @enum;
        }

        /// <summary>
        /// Generates the source file text into a string.
        /// </summary>
        /// <returns>The string containing the source code.</returns>
        public string Generate()
        {
            var source = new StringBuilder();
            Generate(source, 1);
            return source.ToString();
        }

        /// <inheritdoc/>
        internal override void Generate(StringBuilder source, int identation)
        {
            // Generate the file header.
            _ = source.AppendLine(
$@"// THIS IS AN AUTOGENERATED FILE
// <copyright file=""{Name}.cs"" company=""SeminarioIA"">
// Copyright (c) SeminarioIA. All rights reserved.
// </copyright>");

            // Add the references.
            if (References.Count > 0) _ = source.AppendLine();
            foreach (string reference in References)
            {
                _ = source.AppendLine($"using {reference};");
            }

            // Open the namespace.
            _ = source.Append($@"
namespace {Namespace}
{{");

            // Add the code snippets.
            foreach (SourceSnippet snippet in Snippets)
            {
                snippet.Generate(source, identation);
            }

            // Close the namespace.
            _ = source.AppendLine("}");
        }
    }
}
